### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by CarMer194** [timsainb/AVGN#3]
Hello, i was running the bengalese_finch_example, i succesfuly complete the 1.0 and 2.0 program, but in the 3.0-train-autoencoder-network-BF-mds-ae, i got this module error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-b9f47fb5add4> in <module>
----> 1 from avgn.network_analysis.network_analysis import *
      2 import avgn.network.convnet_model as conv
      3 from avgn.network.training import *

ModuleNotFoundError: No module named 'avgn.network_analysis'

Thanks.

**Comment by timsainb** [comment]
Did you install the package? 

Navigate to the main folder of the package (the one with setup.py), then run `python setup.py install` 

For reference, that file is located here:
https://github.com/timsainb/AVGN/blob/master/avgn/network_analysis/network_analysis.py

**Comment by CarMer194** [comment]
Yes i already installed with setup.py, i search in the folder: usr/lib/python3.6/site-package/avgn-0.1.0-py3.6.egg/avgn and i havent seen a reference for network_analysis.

**Comment by CarMer194** [comment]
I found the problem. I found that in the folder build/lib, network and network_analysis folder didnt exist, so i uninstalled avgn, then copied the two folders in bulid/lib and reinstall.
