### ISSUE TITLE
BIRD_DB.xls missing

### ISSUE THREAD

**Issue by robinmeier** [timsainb/AVGN#9]
0.0-Download-BirdDB-Dataset.ipynb relies on a file called BIRD_DB.xls which isn't present in the repository. i think we found it here. i'd suggest you add it?
[BIRD_DB.xls.zip](https://github.com/timsainb/AVGN/files/4123532/BIRD_DB.xls.zip)

**Comment by timsainb** [comment]
Hi @robinmeier, the file is right here:
https://github.com/timsainb/AVGN/blob/master/notebooks/birdsong/cassins_vireo_example/BIRD_DB.xls

**Comment by robinmeier** [comment]
oops :) thanks!
